<!-- <link rel="shortcut icon" href="logo.png" type="image/x-icon"/> -->
<script language="javascript" type="text/javascript" src="script/jquery-3.2.1.min.js"></script>
<script language="javascript" type="text/javascript" src="script/preview.js"></script>
<link href="bootstrap337dist/css/bootstrap.min.css" rel="stylesheet">

<?php
  include('admincheck.php');
?>

<style>
  #menuTop{
    width: 100%;
    height: 50px;
    background-color: cyan;

  }
</style>


<div>
  <div id="">
    <?php
      include('lanphp.inc');
      //include('lancookie.inc');
    ?>
  </div>
</div>
